### ISSUE TITLE
YoLLaVA Links

### ISSUE THREAD

**Issue by Yorizuka** [thaoshibe/thaoshibe#1]
Hello, Sorry if this is not the best place to open this issue, but I am not sure what the appropriate repo would be. Today I ran into YoLLaVA and I did so on your personal website https://thaoshibe.github.io/YoLLaVA/

This is a really cool idea and paper! :D

But both the "code" and "model" links do not seem to actually link to any code or model specific to YoLLaVA.
Would it be possible for you to publish or share the training code and the resulting model weights?
I really want to check it out :^)

Don't worry if the code is not perfect (or even works out of the box) I want to read it to better understand how YoLLaVA was trained!

I opened an issue on the YoLLaVA repo, but the page is on your personal site, so this is why I am also opening an issue here https://github.com/WisconsinAIVision/YoLLaVA/issues/3

**Comment by thaoshibe** [comment]
Hello @Yorizuka , sorry for the late response -- I was really enjoying the summer time without working (hahaha!)
I'm more than happy to publish the code.
Actually I'm just lazy during my summer intern.

I plan to push the code before 25th sept.

If you do not mind a messy version, please refer to: https://github.com/WisconsinAIVision/YoLLaVA/blob/main/train.py
